/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static main.LoginWindow.banca;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Login
     */
    public Login() {
        this.setResizable(false);
        initComponents();
        initLabels();
    }
    
    private void initLabels(){
        
        this.setTitle("Fereastra login");
        
        Password = new javax.swing.JPasswordField();
        Username = new javax.swing.JTextField();
        UsernameText = new javax.swing.JLabel();
        PasswordText = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        
       jLabel1.add(Password);
       jLabel1.add(Username);
       jLabel1.add(Submit);
       jLabel1.add(PasswordText);
       jLabel1.add(UsernameText);
       
       Password.setSize(130,25);
       Username.setSize(130,25);
       UsernameText.setText("Username: ");
       PasswordText.setText("Password: ");
       Submit.setSize(80,30);
       Submit.setText("Submit");
       
       Username.setLocation(360,256);
       Password.setLocation(360,297);
       Submit.setLocation(335,340);
       Submit.addActionListener(this);
       
        
    }
    
    public void actionPerformed(ActionEvent e)
    {
        CheckData();
    }
    
    public void CheckData(){
    
        
        String uname = Username.getText();
        char[] p = Password.getPassword();
        String pass = new String(p);
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/blackjack","root","");
            PreparedStatement ps = con.prepareStatement("select * from users where nume=? and parola=?");
            ps.setString(1, uname);
            ps.setString(2, pass);
            ResultSet rs = ps.executeQuery();
            if (rs.next())
            {
                 banca=rs.getInt("credit");
                 user=rs.getString("nume");
                  dispose();
                  MainW m = new MainW();
                  m.setVisible(true);
            } else
            {
                JOptionPane.showMessageDialog(null,
                   "Nume sau parola gresita");
            }
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
        
    }
    public static void updatebanca(int miza,String nume){
     
               try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/blackjack","root","");
            PreparedStatement ps = con.prepareStatement("update users  set credit=? where nume=?");
            ps.setInt(1, miza);
            ps.setString(2, nume);
            ps.executeUpdate();
    }
                catch (Exception ex)
        {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Assets/background.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jLabel1.getAccessibleContext().setAccessibleName("background");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel UsernameText;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel PasswordText;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Submit;
    public static String user;
    public static int banca;
    ;





}
