/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import Common.MainServerUser;
import Common.Player;
import Common.Table;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author AsX
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     * @param socket
     * @param outToServer
     * @param inFromServer
     * @throws java.io.IOException
     */
    public MainWindow(Socket socket, ObjectOutputStream outToServer, ObjectInputStream inFromServer) throws IOException {
        tables = new ArrayList<>();
        user = new MainServerUser();
        initComponents();
        disableButtons();
        update();
        this.s = socket;
        this.inFromServer = inFromServer;
        this.outToServer = outToServer;
        setTitle();
    }

    private void setTitle(){
        this.setTitle("Blackjack Multiplayer: Lobby");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmasa1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnmasa3 = new javax.swing.JButton();
        btnmasa4 = new javax.swing.JButton();
        btnmasa2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        masa1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        masa2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        masa3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        masa4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        btnmasa1.setText("Table 1");
        btnmasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasa1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        btnmasa3.setText("Table 3");

        btnmasa4.setText("Table 4");

        btnmasa2.setText("Table 2");

        jLabel2.setText("Credit:");

        jLabel5.setText("Players: ");

        jLabel7.setText("Players: ");

        jLabel9.setText("Players:");

        masa3.setName(""); // NOI18N

        jLabel11.setText("Players:");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masa1)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmasa2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masa2)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmasa3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masa3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(masa4)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnmasa4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmasa2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmasa3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmasa4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(masa1)
                            .addComponent(jLabel7)
                            .addComponent(masa2)
                            .addComponent(jLabel9)
                            .addComponent(masa3)
                            .addComponent(jLabel11)
                            .addComponent(masa4))
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );

        btnmasa1.getAccessibleContext().setAccessibleName("btnmasa1");
        btnmasa3.getAccessibleContext().setAccessibleName("btnmasa3");
        btnmasa4.getAccessibleContext().setAccessibleName("btnmasa4");
        btnmasa2.getAccessibleContext().setAccessibleName("btnmasa2");
        jLabel3.getAccessibleContext().setAccessibleName("nume");
        jLabel4.getAccessibleContext().setAccessibleName("credit");
        masa1.getAccessibleContext().setAccessibleName("masa1");
        masa2.getAccessibleContext().setAccessibleName("masa2");
        masa3.getAccessibleContext().setAccessibleName("masa3");
        masa4.getAccessibleContext().setAccessibleName("masa4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasa1ActionPerformed

        Player player = new Player(user.getId(),user.getName(),user.getCredit());
        MainW mainWindows = new MainW(tables.get(0),player);
        mainWindows.setVisible(true);
    }//GEN-LAST:event_btnmasa1ActionPerformed

    
    private void updateInterface(){
        
        sortTables();
        
        if(tables.size()>0){
        for(int i=0;i<tables.size();i++){
                switch(i){
                        case 0:
                            btnmasa1.setEnabled(tables.get(i).isAvailable());
                            break;
                        case 1:
                            btnmasa2.setEnabled(tables.get(i).isAvailable());
                            break;
                        case 2:
                            btnmasa3.setEnabled(tables.get(i).isAvailable());
                            break;
                        case 3:
                            btnmasa4.setEnabled(tables.get(i).isAvailable());
                            break;
                }
            
            switch (i) {
                case 0:
                    masa1.setText(Integer.toString(tables.get(i).getNumOfPlayers()));
                    break;
                case 1:
                    masa2.setText(Integer.toString(tables.get(i).getNumOfPlayers()));
                    break;
                case 2:
                    masa3.setText(Integer.toString(tables.get(i).getNumOfPlayers()));
                    break;
                case 3:
                    masa4.setText(Integer.toString(tables.get(i).getNumOfPlayers()));
                    break;
            }
        }
        
        }
        else{
              btnmasa1.setEnabled(false);
              btnmasa2.setEnabled(false);
              btnmasa3.setEnabled(false);
              btnmasa4.setEnabled(false);
              masa1.setText("");
              masa2.setText("");
              masa3.setText("");
              masa4.setText("");
        }
        if(user.getName() != null){
            jLabel3.setText(user.getName());
        }
        if(user.getCredit() != 0){
            jLabel4.setText(Integer.toString(user.getCredit())); 
        }
    }
    
    private void sortTables(){
        
        
    }
    
    private void disableButtons(){
    btnmasa1.setEnabled(false);
    btnmasa2.setEnabled(false);
    btnmasa3.setEnabled(false);
    btnmasa4.setEnabled(false);
    }
    
    private void update() throws IOException{
               new Thread() {
                @Override
                public void run() {
                    try{
                        while(!Thread.interrupted()){
                            try {
                                Object received = inFromServer.readObject();
                                if(received instanceof ArrayList){
                                    ArrayList<Table> tablesReceived = (ArrayList<Table>) received;
                                    tables.clear();
                                    tables=tablesReceived;
                                }
                                if(received instanceof MainServerUser){
                                    MainServerUser receivedUser = (MainServerUser) received;
                                    user = new MainServerUser();
                                    user = receivedUser;
                                }
                                updateInterface();

                            } catch (ClassNotFoundException ex) {
                                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                    catch (IOException ex) {
                        Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }.start();
    }
   
            
       
               
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmasa1;
    private javax.swing.JButton btnmasa2;
    private javax.swing.JButton btnmasa3;
    private javax.swing.JButton btnmasa4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel masa1;
    private javax.swing.JLabel masa2;
    private javax.swing.JLabel masa3;
    private javax.swing.JLabel masa4;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Table> tables;
    private MainServerUser user;
    private final Socket s;
    private final ObjectOutputStream outToServer;
    private final ObjectInputStream inFromServer;
}
